codecov:
  branch: master


coverage:
  status:
    patch: false

  range: 40..90     # First number represents red, and second represents green
                    # (default is 70..100)


# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - dina-datamodel-slim/src/main/java/se/nrm/dina/datamodel/impl/
  - dina-datamodel-slim/src/main/java/se/nrm/dina/datamodel/BaseEntity.java
